Capstone project
Yonashenok/first-capstone-project pull request #1
Opened 2023-05-23 07:10 UTC by Yonashenok

## what I did
* making sure no linter error
* follow design guidelines
* personalize the content in my page
* use bootstrap and CSS
* responsive for both home and about page
* added link to home page when user click on logo 
* added link to nav bar to switch between home and about page
* created mobile menu and when user click it will scroll in the section view
* added the feature speaker page dynamically in JavaScript

thanks 😀

2023-05-23 15:04 UTC, NahnahAJ commented
## Project Status: INVALIDATED :red_circle: 
Hi @Yonashenok , 

While you made a great effort in this project, I can't go ahead and review your code.
<img src="https://media2.giphy.com/media/TiUYdWptTqn8yOk1Dp/giphy.gif"/>

## Invalid Code Review Request

- [ ]  This is because your README contains the right details. However, you have altered the original `Table of contents` and you're also missing some of the `header/sections` of the [Microverse README Template](https://github.com/microverseinc/readme-template)](https://github.com/microverseinc/readme-template). This makes your project incomplete as every section of the readme template is required except for the `FAQ section` which is optional.
- [ ]  So please make sure to add all the missing headers/sections in the README template to your project and fill in all the necessary contents :+1: and Please ensure that The README also contains the original complete list of `Table of Contents` and ensure that when a topic is clicked on in the table of contents, it takes you to its related section :wink:

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-23 15:18 UTC, divinecharlotte requested changes
Hi @Yonashenok       , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- linters are passing 👍 
- Descriptive Pr 👍 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️


_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 15:18 UTC, divinecharlotte commented on README.md
> +- Twitter: [@yonashenok](https://twitter.com/twitterhandle)
- [ ] kindly consider adding a working link to your Twitter account in the author section  to give a good user experience to the people visiting your readme

2023-05-23 15:18 UTC, divinecharlotte commented on README.md
> +- [Live Demo]()
- [ ] kindly consider deploying your project and add the real live demo link. you can do so using by making use of GitHub Pages to deploy the web pages as it will allow you to host a static website directly from a GitHub repository and it will improve the user experience 😃

2023-05-23 15:18 UTC, divinecharlotte commented on README.md
> +```
- [ ] kindly consider adding the right way to start your project to make your readme more interactive to the people visiting it 😀

2023-05-23 15:18 UTC, divinecharlotte commented on home.html
> +    </nav>
- [ ] Kindly consider making sure that  this navbar contains 
1.  a top dark bar and a bottom white bar.
2. The top short bar section with social media links, logout, and language links is aligned to the right. to make your design looks exactly as the provided one 
- check the images below for more clarification
- your design 👇 
<img width="966" alt="Screen Shot 2023-05-23 at 15 41 53" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/8ad46515-5fd1-4cd9-a0e6-1e7c85ea4784">


- provided design 👇 
<img width="973" alt="Screen Shot 2023-05-23 at 15 42 42" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/3d730756-885d-4eb3-b119-1a91d6733cda">
  consider fixing the above on both pages either home or about

2023-05-23 15:18 UTC, divinecharlotte commented on home.html
> +    </footer>
- [ ] kindly consider sticking to the given design as much as possible by making sure that your footer on the home page looks exactly like the one in the design by respecting both margins and padding to make an exact duplicate of the given design check the images below to see the difference and fix them 👇 
- your design 👇 
<img width="1421" alt="Screen Shot 2023-05-23 at 15 50 49" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/3f2f9c48-d4e2-4920-a22e-30fb05cab025">

- provided design 👇 
<img width="973" alt="Screen Shot 2023-05-23 at 15 51 47" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/e578798b-de17-4528-b939-47a693ed8814">


- [ ] kindly consider not displaying any footer on the home page of the mobile version  as well  so as to deliver what's expected

2023-05-23 15:18 UTC, divinecharlotte commented on src/about.html
> +    </footer>
- [ ] kindly consider making sure that the footer on the About section looks exactly like the second footer you have on the home section but in a dark background so as to stick to the provided design as much as possible 
- check the images below for a better understanding of what I mean here \
- your design 👇 
<img width="1426" alt="Screen Shot 2023-05-23 at 16 05 57" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/b536a9d6-9eca-4f9e-8f71-06b5cf5b627c">

- provided design 👇 
<img width="866" alt="Screen Shot 2023-05-23 at 16 07 00" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/172b6e82-69ff-41b7-ad36-8363f91fe444">

2023-05-23 15:18 UTC, divinecharlotte commented on home.html
> +    </section>
- [ ] kindly consider sticking to the provided design as much as possible you are only to change the content of the section, not the design to full fill the below 👇 requirement 
<img width="1054" alt="Screen Shot 2023-05-23 at 16 15 24" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/0e2dc26d-2b12-4837-877c-16d22c21d5bd">
 

check on the screen shoots am adding below and while fixing your design make sure that this section looks exactly as the one given in the design 

- your design 👇 
<img width="939" alt="Screen Shot 2023-05-23 at 16 17 54" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/769bd059-5f6a-4ef5-8c1f-81867961b608">

- provided design 👇 
<img width="977" alt="Screen Shot 2023-05-23 at 16 22 26" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/5f2c27ce-d262-494d-9624-133bca73e0a4">

2023-05-23 15:18 UTC, divinecharlotte commented on home.html
> +        <div
- [ ] Kindly consider including the line of text at the bottom. of these cards in this div to make your design look exactly as the one is given and also consider wrapping all its contents in a section tag for semantic reasons
- check the images below for more clarification 👇 
- your design 👇 
<img width="958" alt="Screen Shot 2023-05-23 at 16 30 47" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/d3aae30b-5ab7-48e4-abf2-d7b924043e60">


- given design 👇 
<img width="973" alt="Screen Shot 2023-05-23 at 16 31 45" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/017f9a01-aa36-4a07-8d59-ba3795d56d72">

2023-05-23 15:18 UTC, divinecharlotte commented on src/js/home.js
> +  });
- [ ] kindly consider making sure that all this is wrapped in a section tag for semantic reasons and make sure that that section will be looking exactly like the one provided on in the design to make sure that you deliver design that is on the high standard 
check the images below
-your design 👇 
<img width="939" alt="Screen Shot 2023-05-23 at 16 40 55" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/a1a7b14a-6af2-4fce-a9c1-6a48486f2da8">


- provided design 👇 
<img width="980" alt="Screen Shot 2023-05-23 at 16 46 56" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/b946fe3c-179c-46e5-9765-cad18d9289ef">
 ☠️ consider fixing everything on both screen sizes

2023-05-23 15:18 UTC, divinecharlotte commented on src/js/home.js
> +};
- [ ] kindly consider making sure that section looks the same as the one in the provided design on the mobile version so as to stick to the given design check the images below  for more clarification and fix each issue underlined 
- your design 👇 
<img width="370" alt="Screen Shot 2023-05-23 at 16 54 18" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/51ab268e-e9da-4cbc-b584-5879c1f6a1cb">


- given design 👇 
<img width="454" alt="Screen Shot 2023-05-23 at 16 55 12" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/f0ce2f1d-6c90-4527-9df7-05a7a0531ddc">

2023-05-23 15:18 UTC, divinecharlotte commented on src/about.html
> +            <div
- [ ] Kindly consider making sure that this title looks exactly the same as the one provided in the design to make sure that your design is of a high standard and also remember to add the small heading with your own content above the main heading 
- your design 👇 
<img width="374" alt="Screen Shot 2023-05-23 at 17 04 55" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/43097627-1648-4928-a532-99b14006aeff">

- given design 👇 
<img width="453" alt="Screen Shot 2023-05-23 at 17 05 27" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/9c2a5b55-6534-4639-bb03-b15115447bdc">


☠️ kindly consider doing so on both screen size

2023-05-23 15:18 UTC, divinecharlotte commented on src/about.html
> +                  />
- [ ] kindly consider making sure that this section looks exactly like the one given in the design on Behance to meet the project design requirement and remember you are only allowed to change the content but the design remains the same 

- your design 👇 
<img width="370" alt="Screen Shot 2023-05-23 at 17 13 17" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/a92bec45-4128-45e8-9efb-9f7afb36447b">

- provided design 👇 
<img width="447" alt="Screen Shot 2023-05-23 at 17 13 57" src="https://github.com/Yonashenok/first-capstone-project/assets/60146030/3ef9ed8c-eb9a-46b3-9b8f-40bd3d3902d9">

- [ ] While fixing that make sure that on both screen sizes, the design remains the same exactly as the one on Behance
either the way cards are displayed the design the background color the texts on the card like everything to deliver whats expected

2023-05-24 13:19 UTC, abdallahmalima requested changes
Hi @Yonashenok , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Acknowledgements section✔
- Project deployed✔
- `Home` page and `About` page✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 13:19 UTC, abdallahmalima commented on index.html
> +    </section>
- [ ] 🙏Please add padding to the bottom of the content in this section to match the original design. This adjustment will enhance the appearance 👩‍🦰of your website and ensure it resembles the original design.

Your design:
![image](https://github.com/Yonashenok/first-capstone-project/assets/63445083/c5aac895-2847-4934-8b17-cdd803f23717)

Original design:
![image](https://github.com/Yonashenok/first-capstone-project/assets/63445083/d6e1227a-d5cf-45ad-ab8c-20add37fa8fc)

2023-05-24 13:19 UTC, abdallahmalima commented on index.html
> +            class="footer-line border-bottom border-5 mb-5 border-danger"
- [ ] 🙏Please arrange all the cards in this section horizontally for the desktop🖥 screen size, so that they resemble the original design. This arrangement will enhance the appearance 👩‍🦰of your website and ensure it resembles the original design.

Your design:
![image](https://github.com/Yonashenok/first-capstone-project/assets/63445083/c0d077ef-91d1-4d6b-a3ad-bc5db9e2375a)

Original design:
![image](https://github.com/Yonashenok/first-capstone-project/assets/63445083/110126e8-1ad5-4a63-a2d6-a054ea8329e5)

2023-05-24 13:19 UTC, abdallahmalima commented on index.html
> +          />
- [ ] 🙏Please add padding to the bottom of the content in this section to match the original design. This adjustment will enhance the appearance 👩‍🦰of your website and ensure it resembles the original design.

Your design:
![image](https://github.com/Yonashenok/first-capstone-project/assets/63445083/817b6d2f-3be5-4f94-b7b1-0ce38f4859c4)

Original design:
![image](https://github.com/Yonashenok/first-capstone-project/assets/63445083/259e5081-7c31-4748-bf0d-47468bafe86a)

2023-05-24 13:19 UTC, abdallahmalima commented on index.html
> +    </footer>
- [ ] 🙏Please add padding to the bottom of the content in this section to match the original design. This adjustment will enhance the appearance 👩‍🦰of your website and ensure it resembles the original design.

Your design:
![image](https://github.com/Yonashenok/first-capstone-project/assets/63445083/6af45abd-00f4-4515-a5a7-ba09c165569e)

Original design:
![image](https://github.com/Yonashenok/first-capstone-project/assets/63445083/f52628be-6a27-406b-a906-c4c7d6de17a8)

2023-05-24 14:38 UTC, Yonashenok commented on index.html
> +            class="footer-line border-bottom border-5 mb-5 border-danger"
## what I did
>
>
![image](https://github.com/Yonashenok/first-capstone-project/assets/99332080/00eb2aa4-6504-4e84-8418-e0e9690d1c79)

2023-05-24 14:38 UTC, Yonashenok commented on index.html
> +          />
## what I did
>
>
![image](https://github.com/Yonashenok/first-capstone-project/assets/99332080/f9b71bcb-18b5-43cf-872b-c5efffd79a63)

>
>
![image](https://github.com/Yonashenok/first-capstone-project/assets/99332080/4aabe3de-4dd1-432a-a3ce-f615fffe52a1)

2023-05-24 14:38 UTC, Yonashenok commented on index.html
> +    </section>
## what i did
>
>
![image](https://github.com/Yonashenok/first-capstone-project/assets/99332080/bcd1557d-554a-42d4-b390-9fcaf5dc8939)

2023-05-24 14:44 UTC, ShadyShawkat approved these changes
## Hi @Yonashenok, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 
- Good overall design ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 16:21 UTC, merged

2023-05-29 08:06 UTC, NahnahAJ commented
## Project Status: APPROVED :green_circle: 
Hi @Yonashenok , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
- All linters are passing ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Good overall design ✔️ 
 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._